apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
type: Opaque
data:
  # Users must generate these themselves: echo -n 'admin' | base64
  MINIO_ROOT_USER: YOUR_BASE64_USER_HERE
  MINIO_ROOT_PASSWORD: YOUR_BASE64_PASSWORD_HERE
